version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - obdata_dev:/var/lib/openbazaar
      - .:/go/src/github.com/OpenBazaar/openbazaar-go
  server:
    image: openbazaar/server
    ports:
      - 5001
      - 5002
      - 10005
    volumes:
      - obdata:/var/lib/openbazaar

volumes:
  obdata:
  obdata_dev:
